mlist=['akonadi', 'akonadi-search', 'baloo-widgets', 'extra-cmake-modules', 'grantlee', 'gwenview', 'kate', 'kcalc', 'kdepim-runtime', 'kdepimlibs', 'kdesrc-build', 'kdevplatform', 'kmix', 'konsole', 'ksnapshot', 'kwalletmanager', 'libdbusmenu-qt', 'libkgapi', 'libkomparediff2', 'okular', 'phonon', 'phonon-gstreamer', 'phonon-vlc', 'plasmate', 'polkit-qt-1', 'print-manager']
print(len(mlist))
mlist=[]
strng="solid kinit kservice sonnet attica kcompletion kactivities kiconthemes frameworkintegration kdewebkit kded plasma-framework kemoticons kpackage kcrash ktexteditor kcodecs kdesignerplugin kauth kdnssd kxmlgui kcmutils kjsembed kguiaddons kross kdbusaddons kconfigwidgets kdelibs4support khtml knotifications kdoctools kio kdesu kpty kplotting kparts kcoreaddons kitemviews kjs kitemmodels kmediaplayer kunitconversion kidletime kwallet knotifyconfig kconfig ktextwidgets kjobwidgets krunner karchive kimageformats kglobalaccel kdeclarative networkmanager-qt knewstuff kbookmarks kxmlrpcclient ki18n kwindowsystem kapidox threadweaver kwidgetsaddons baloo plasma-nm kmenuedit khelpcenter kinfocenter kwrited user-manager khotkeys breeze libbluedevil libksysguard kcm-touchpad kde-cli-tools sddm-kcm libkscreen kfilemetadata oxygen plasma-desktop polkit-kde-agent-1 powerdevil kscreen systemsettings kwin ksysguard muon kde-gtk-config bluedevil kwayland plasma-workspace milou oxygen-fonts libmm-qt kdecoration ksshaskpass kdeplasma-addons kio-extras kblog kalarmcal akonadi-calendar gpgmepp syndication kmailtransport kmime kmbox kimap kpimtextedit kontactinterface kholidays kcalutils kcalcore kidentitymanagement ktnef kcontacts kldap"
mlist.extend(strng.split(' '))
makepkg=set(mlist)
kstrng="grantlee, libdbusmenu-qt, taglib, extra-cmake-modules, attica, kconfig, ki18n, kdbusaddons, kwindowsystem, kcoreaddons, kcrash, karchive, kdoctools, kservice, kitemviews, kauth, kcodecs, kguiaddons, kwidgetsaddons, kconfigwidgets, kiconthemes, kglobalaccel, kcompletion, sonnet, ktextwidgets, kxmlgui, kcmutils, solid, kjobwidgets, kbookmarks, phonon, knotifications, kwallet, kio, kdeclarative, kactivities, kunitconversion, kinit, kparts, kplotting, kdewebkit, kdesignerplugin, kdelibs4support, kded, kdnssd, kemoticons, kjs, khtml, kidletime, kjsembed, kitemmodels, knewstuff, knotifyconfig, frameworkintegration, kpty, kdesu, kross, ktexteditor, threadweaver, kpackage, plasma-framework, kxmlrpcclient, kdesrc-build, polkit-qt-1, phonon-vlc, phonon-gstreamer, akonadi, kimageformats, kapidox, krunner, kmediaplayer, networkmanager-qt, ksshaskpass, kde-gtk-config, oxygen-fonts, libmm-qt, plasma-nm, kdecoration, kwayland, libksysguard, kwin, kfilemetadata, baloo, milou, khelpcenter, kde-cli-tools, kio-extras, breeze, libkscreen, plasma-workspace, kmenuedit, systemsettings, polkit-kde-agent-1, kwrited, kscreen, khotkeys, libbluedevil, muon, powerdevil, kdeplasma-addons, oxygen, bluedevil, user-manager, kinfocenter, ksysguard, plasma-desktop, sddm-kcm, libkomparediff2, kdevplatform, plasmate, kwalletmanager, baloo-widgets, konsole, kate, kde-baseapps, gwenview, okular, ksnapshot, kcalc, print-manager, kmix, kcontacts, kcalcore, syndication, kblog, kpimtextedit, kidentitymanagement, kcalutils, kholidays, kmime, kimap, kldap, kmbox, kontactinterface, ktnef, gpgmepp, kdepimlibs, kmailtransport, akonadi-search, libkgapi, kalarmcal, akonadi-calendar, kdepim-runtime".replace(' ','')
kdesrcbuild=set(kstrng.split(','))

print(kdesrcbuild - makepkg)
print(len(kdesrcbuild - makepkg))
print(makepkg - kdesrcbuild)

for i in kstrng.split(','):
    if i not in kdesrcbuild - makepkg:
        print("kde5-%s-git" % i,end=' ')