#!/usr/bin/bash

export KF5=/opt/kf5
export XDG_DATA_DIRS=$KF5/share:$XDG_DATA_DIRS:/usr/share
export XDG_CONFIG_DIRS=$KF5/etc/xdg:$XDG_CONFIG_DIRS:/etc/xdg
export PATH=$KF5/bin:$QTDIR/bin:$PATH
export QT_PLUGIN_PATH=$KF5/lib/plugins:$KF5/lib/x86_64-linux-gnu/plugins
export QML2_IMPORT_PATH=$KF5/lib/qml:$KF5/lib/x86_64-linux-gnu/qml
export KDE_SESSION_VERSION=5
export KDE_FULL_SESSION=true

export XDG_DATA_HOME=$HOME/.kde5/.local5
export XDG_CONFIG_HOME=$HOME/.kde5/.config5
export XDG_CACHE_HOME=$HOME/.kde5/.cache5

eval `dbus-launch`
kdeinit5