#!/usr/bin/bash

export KF5=/opt/kf5
export QTDIR=/usr/lib/qt
export XDG_DATA_DIRS=$KF5/share:$XDG_DATA_DIRS:/usr/share
export XDG_CONFIG_DIRS=$KF5/etc/xdg:$XDG_CONFIG_DIRS:/etc/xdg
export PATH=$KF5/bin:$QTDIR/bin:$PATH
export QT_PLUGIN_PATH=$KF5/lib/plugins:$QTDIR/plugins:$QT_PLUGIN_PATH
export QML2_IMPORT_PATH=$KF5/lib/qml:$QTDIR/qml
export KDE_SESSION_VERSION=5
export KDE_FULL_SESSION=true

export XDG_DATA_HOME=$HOME/.kde5/.local5
export XDG_CONFIG_HOME=$HOME/.kde5/.config5
export XDG_CACHE_HOME=$HOME/.kde5/.cache5

cat > ~/.xinitrc << EOF
# Begin .xinitrc

exec dbus-launch --exit-with-session /opt/kf5/bin/startkde

# End .xinitrc
EOF

startx  -- :1